# Generated by Django 5.0.6 on 2024-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranjections', '0002_transaction_delete_tranjections'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bankdurft',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
