# Generated by Django 5.0.6 on 2024-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranjections', '0005_alter_transfer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
