# Generated by Django 5.0.6 on 2024-08-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tranjections', '0006_alter_transfer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_account',
        ),
    ]
