# Generated by Django 5.0.6 on 2024-08-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tranjections', '0007_remove_transaction_transfer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bankdurft',
        ),
    ]
