# Generated by Django 5.0.6 on 2024-08-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='birthday',
            new_name='birth_date',
        ),
    ]
