# Generated by Django 5.0.6 on 2024-08-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_birthday_userbankaccount_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='Balance',
            new_name='balance',
        ),
    ]
