# Generated by Django 5.0.6 on 2024-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_balance_userbankaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='bankdurft',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
